// example/angular/universal/src/app/todos/todos.component.ts
import {
  Component,
  Input,
  EventEmitter,
  Output,
  ChangeDetectorRef,
  OnInit,
  OnDestroy
} from '@angular/core';
import { Todo } from '../models/todo';
import { TodoFilter } from './todos.pipe';

@Component({
  templateUrl: 'todos.component.html',
  selector: 'app-todos'
})
export class TodosComponent implements OnInit, OnDestroy {
  @Input() todos: Todo[] | null;
  @Output() update = new EventEmitter();
  @Output() delete = new EventEmitter();
  @Output() add = new EventEmitter();
  private hashListener: EventListenerOrEventListenerObject;

  constructor(private cdRef: ChangeDetectorRef) {}

  ngOnInit() {
    if (typeof window !== 'undefined') {
      window.addEventListener(
        'hashchange',
        (this.hashListener = () => this.cdRef.markForCheck())
      );
    }
  }

  ngOnDestroy() {
    if (typeof window !== 'undefined') {
      window.removeEventListener('hashchange', this.hashListener);
    }
  }

  get filterValue(): TodoFilter {
    if (typeof window !== 'undefined') {
      return window.location.hash.replace(/^#\//, '') as TodoFilter || TodoFilter.All;
    }
    return TodoFilter.All;
  }

  get itemsLeft() {
    return (this.todos || []).filter(t => !t.completed).length;
  }

  clearCompleted() {
    (this.todos || [])
      .filter(t => t.completed)
      .forEach(t => this.delete.emit(t));
  }
}

<section class="main">
  <input id="toggle-all" class="toggle-all" type="checkbox">
  <label for="toggle-all">Mark all as complete</label>
  <ul class="todo-list">
    <!-- These are here just to show the structure of the list items -->
    <!-- List items should get the class `editing` when editing and `completed` when marked as completed -->

    <app-todo *ngFor="let todo of todos | todosFilter: filterValue" [todo]="todo" (delete)="delete.emit($event)" (update)="update.emit($event)" (delete)="delete.emit($event)"></app-todo>
  </ul>
</section>
<!-- This footer should hidden by default and shown when there are todos -->
<footer class="footer">
  <!-- This should be `0 items left` by default -->
  <span class="todo-count"><strong>{{itemsLeft}}</strong> item left</span>
  <!-- Remove this if you don't implement routing -->
  <ul class="filters">
    <li>
      <a [class.selected]="filterValue === 'all'" href="#/">All</a>
    </li>
    <li>
      <a [class.selected]="filterValue === 'active'" href="#/active">Active</a>
    </li>
    <li>
      <a [class.selected]="filterValue === 'completed'" href="#/completed">Completed</a>
    </li>
  </ul>
  <!-- Hidden if no completed items are left ↓ -->
  <button class="clear-completed" (click)="clearCompleted()">Clear completed</button>
</footer>

// example/next/components/todos.tsx
import { useState } from 'react';
import { Todo as TodoItem } from '../models/store';
import Todo, { OnDelete, OnEdit } from './todo';

export enum TodoFilter {
  All = 'all',
  Completed = 'completed',
  Active = 'active'
}

export default ({
  todos,
  onDelete,
  onEdit
}: {
  todos: TodoItem[];
  onDelete: OnDelete;
  onEdit: OnEdit;
}) => {
  const [activeState, setActiveState] = useState(
    typeof window !== 'undefined'
      ? (window.location.hash.replace(/^#\//, '') as TodoFilter) ||
          TodoFilter.All
      : TodoFilter.All
  );

  const clearCompleted = () => {};
  const itemsLeft = todos.filter(t => !t.completed).length;

  return (
    <>
      <section className="main">
        <input id="toggle-all" className="toggle-all" type="checkbox" />
        <label htmlFor="toggle-all">Mark all as complete</label>
        <ul className="todo-list">
          {todos.filter(t => {
            switch (activeState) {
              case TodoFilter.Active:
                return !t.completed;
              case TodoFilter.Completed:
                return t.completed;
              default:
                return true;
            }
          }).map(t => (
            <Todo onDelete={onDelete} onEdit={onEdit} key={t.id} todo={t} />
          ))}
        </ul>
      </section>
      <footer className="footer">
        <span className="todo-count">
          <strong>{itemsLeft}</strong> item left
        </span>
        <ul className="filters">
          <li>
            <a
              onClick={() => setActiveState(TodoFilter.All)}
              className={activeState === TodoFilter.All ? 'selected' : ''}
              href="#/"
            >
              All
            </a>
          </li>
          <li>
            <a
              onClick={() => setActiveState(TodoFilter.Active)}
              className={activeState === TodoFilter.Active ? 'selected' : ''}
              href="#/active"
            >
              Active
            </a>
          </li>
          <li>
            <a
              onClick={() => setActiveState(TodoFilter.Completed)}
              className={
                activeState === TodoFilter.Completed ? 'selected' : ''
              }
              href="#/completed"
            >
              Completed
            </a>
          </li>
        </ul>
        <button className="clear-completed" onClick={clearCompleted}>
          Clear completed
        </button>
      </footer>
    </>
  );
};
